### ISSUE TITLE
check all the related services 

### ISSUE THREAD

**Issue by 12rambau** [gee-community/pygaul#32]
verify that everything still works since the move to gee-community: 
- [x] github actions 
- [x] devcontainer 
- [x] RDT
- [x] coverage
- [x] pypi
- [x] conda

**Comment by 12rambau** [comment]
@giswqs I tried to reactivate the RDT hook that build the documentation but it seems I don't have sufficient rights. 

<img width="622" alt="image" src="https://github.com/gee-community/pygaul/assets/12596392/a6a34c39-07a8-4320-9415-dd491d8bdad4">

Could you advice what I should do ?

**Comment by 12rambau** [comment]
integration are way much more straight forward than webhooks + it will allow me to deploy the one for gee-tools the same way without much more configuration. Any reason why you would not OAuth RDT in the organization ? (the question can be extended to codecov I assume you received the request by now)

**Comment by giswqs** [comment]
Try again. It should work now. As I am not the original admin of the org, I try to avoid making changes at the org level without consulting with the admins.

**Comment by 12rambau** [comment]
I checked the other orgs I'm working in and I think the problem comes down to the simple fact that i'm not the owner. 2 options: 
- I add you to documentation maintainers and you set-up the hook
- You grant me ownership for 30 min, I create the hook and I set me back to maintainer

**Comment by giswqs** [comment]
I have granted you temporary ownership.

**Comment by 12rambau** [comment]
I made it, took me while to understand but it's done. and I should not bother you again, you can downgrade me
